<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>73f3642e-a333-4d9c-a6c1-443c78b7cc3d</elementGuidId>
    <imagePath></imagePath>
    <name>button_checkout</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#checkout</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'checkout') and equals(@name,'checkout') and equals(@class,'btn btn_action btn_medium checkout_button ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_action btn_medium checkout_button </value>
        <webElementGuid>48a496a8-b826-4567-9cd7-814efb93ad06</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>checkout</value>
        <webElementGuid>3418cf83-a92e-4175-a667-099e8749243a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>checkout</value>
        <webElementGuid>998533ae-bf4d-46b4-9cb5-38d0a0970954</webElementGuid>
    </webElementProperties>
</WebElementEntity>